### ISSUE TITLE
Error trying to run in Processing

### ISSUE THREAD

**Issue by Rhys79** [konsumer/arduinoscope#1]
I'm trying to set this up.  I have the firmata firmware loaded on my Uno, I have the arduino-firmata library and the arduinoscope library loaded into the libraries directory for Processing.  I load the arduinoscope example in Processing, click run, and I get a "expected RBRACK, found '2'" error in reference to the "int[2] dim" near the top of the program.  Not sure what's going on, I have no experience with Processing yet....

**Comment by konsumer** [comment]
I haven't done any testing with this, yet.  Try the [version on google code](http://code.google.com/p/arduinoscope/) until I get some time to work on it.

**Comment by konsumer** [comment]
This should be resolved now, give it a try. I think the COM port needed to be selectable.
