### ISSUE TITLE
Can you write the specifications/features 

### ISSUE THREAD

**Issue by acseckin** [konsumer/arduinoscope#2]
Its not an issue just a suggession. Can you write the specifications/features arduinoscope. For example witch functions can be generatable and/or bandwith etc.

**Comment by konsumer** [comment]
The bandwidth is closely tied to the speed that you can get data from Firmata. on a teensy, for example, it is a lot faster than on Uno.  The scope is not really meant to be an awesome replacement for a pro digital oscilloscope, more of a learning tool for reading what's going on and learning about programming processing/arduino.  That said, I am happy to put specs in the README, if people want to do some speed tests.
