### ISSUE TITLE
Schematics of the arduinoscope

### ISSUE THREAD

**Issue by mansuleman** [konsumer/arduinoscope#4]
You are talking about original oscilloscope in the readme. And then link to the instructions but I'm not sure the schematics of the arduinoscope corresponds to the instruction. Where can I find the schematics for the arduinoscope?

**Comment by lshachar** [comment]
I don't think that there are any schematics. you can connect a variable voltage to your Arduino analog inputs, at their operating range (usually 0-5vdc).

**Comment by konsumer** [comment]
Yeh, no schematic needed, just hook your inputs to analog-in pins of arduino. I am going to close this for now, but feel free to add comments if that doesn't resolve your issue.
